import Ajv2020 from 'ajv/dist/2020';
import definitionSchema from './schemas/definition-manifest.schema.json';
import effectiveSchema from './schemas/effective-manifest.schema.json';
import type { SHDefinitionManifest, SHManifestDiff, SHManifestValidationResult } from './types';
import type { SHEffectiveManifest } from '../core';
const ajv = new Ajv2020({ allErrors: true, strict: false });
const definitionValidator = ajv.compile(definitionSchema);
const effectiveValidator = ajv.compile(effectiveSchema);
const result = (
  valid: boolean,
  errors: typeof definitionValidator.errors,
): SHManifestValidationResult => ({
  valid,
  errors: (errors ?? []).map(
    (error) => `${error.instancePath || '/'} ${error.message ?? 'invalid'}`,
  ),
});
export const validateSHDefinitionManifest = (value: unknown): SHManifestValidationResult =>
  result(definitionValidator(value), definitionValidator.errors);
export const validateSHEffectiveManifest = (value: unknown): SHManifestValidationResult =>
  result(effectiveValidator(value), effectiveValidator.errors);
export function lintSHDefinitionManifest(
  manifest: SHDefinitionManifest,
): SHManifestValidationResult {
  const errors: string[] = [];
  const keys = new Set<string>();
  for (const resource of manifest.resources) {
    if (keys.has(resource.key)) errors.push(`duplicate resource: ${resource.key}`);
    keys.add(resource.key);
    const actions = new Set<string>();
    for (const action of resource.actions) {
      if (actions.has(action.key)) errors.push(`duplicate action: ${resource.key}/${action.key}`);
      actions.add(action.key);
    }
  }
  for (const resource of manifest.resources)
    if (resource.parent && !keys.has(resource.parent))
      errors.push(`invalid parent: ${resource.key} -> ${resource.parent ?? ''}`);
  for (const route of manifest.routes ?? []) {
    if (route.resource && !keys.has(route.resource))
      errors.push(`unknown route resource: ${route.resource}`);
    const resource = manifest.resources.find((item) => item.key === route.resource);
    if (route.action && !resource?.actions.some((action) => action.key === route.action))
      errors.push(`unknown route action: ${route.resource ?? ''}/${route.action}`);
  }
  return { valid: errors.length === 0, errors };
}
export function diffSHDefinitionManifests(
  before: SHDefinitionManifest,
  after: SHDefinitionManifest,
): SHManifestDiff {
  const additive: string[] = [];
  const deprecated: string[] = [];
  const breaking: string[] = [];
  const oldResources = new Map(before.resources.map((resource) => [resource.key, resource]));
  const newResources = new Map(after.resources.map((resource) => [resource.key, resource]));
  for (const [key, resource] of newResources) {
    const old = oldResources.get(key);
    if (!old) {
      additive.push(`resource:${key}`);
      continue;
    }
    const oldActions = new Map(old.actions.map((action) => [action.key, action]));
    for (const action of resource.actions) {
      if (!oldActions.has(action.key)) additive.push(`action:${key}/${action.key}`);
      if (action.deprecated && !oldActions.get(action.key)?.deprecated)
        deprecated.push(`action:${key}/${action.key}`);
    }
    for (const action of old.actions)
      if (!resource.actions.some((candidate) => candidate.key === action.key))
        breaking.push(`action:${key}/${action.key}`);
  }
  for (const key of oldResources.keys())
    if (!newResources.has(key)) breaking.push(`resource:${key}`);
  return { additive, deprecated, breaking };
}
export function generateSHManifestConstants(manifest: SHDefinitionManifest): string {
  const resources = manifest.resources
    .map((resource) => `  ${JSON.stringify(resource.key)}: ${JSON.stringify(resource.key)},`)
    .join('\n');
  const actions = manifest.resources
    .flatMap((resource) =>
      resource.actions.map(
        (action) =>
          `  ${JSON.stringify(`${resource.key}.${action.key}`)}: ${JSON.stringify(action.key)},`,
      ),
    )
    .join('\n');
  return `// Generated by sh-core-ui. Do not edit.\nexport const resources = {\n${resources}\n} as const;\nexport const actions = {\n${actions}\n} as const;\n`;
}
export type { SHEffectiveManifest };
